import Providers from "@/lib/Providers";
import "./globals.css";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import SessionProvider from "../components/SessionProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <>
      <html lang='en'>
        <body>
          <Providers>
            <SessionProvider session={session}>{children}</SessionProvider>
          </Providers>
        </body>
      </html>
    </>
  );
}
